docker-compose update
HCL-TECH-SOFTWARE/dx-docker-compose pull request #12
Opened 2022-02-07 10:43 UTC by soorajoasis

The updated version of docker compose solution for dx. 

Changes.

The new DAM database system is configured.
Introduced nginx reverse proxy.

2022-02-07 10:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/HCL-TECH-SOFTWARE/dx-docker-compose?pullRequest=12) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/HCL-TECH-SOFTWARE/dx-docker-compose?pullRequest=12) before we can accept your contribution.<br/><hr/>**soorajoasis** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/HCL-TECH-SOFTWARE/dx-docker-compose?pullRequest=12) it.</sub>

2022-02-07 14:08 UTC, timpeteler requested changes

2022-02-07 14:08 UTC, timpeteler commented on nginx.conf
> +                server_name     localhost;
this shouldn't just be localhost
![image](https://user-images.githubusercontent.com/4126123/152802285-42c68254-1097-48cb-a905-162ec96deb8d.png)

2022-02-07 14:08 UTC, timpeteler commented on nginx.conf
> +                # DAM UI
duplication

2022-02-07 14:08 UTC, timpeteler commented on nginx.conf
> +user  nginx;
I guess you just copied the nginx.conf from the PR check env, right?
I'd ask you to distill it down to the bare minimum of what is needed (maybe just the proxy rules?)

2022-02-10 13:45 UTC, timpeteler requested changes

2022-02-13 18:30 UTC, soorajoasis commented on README.md
> +Example: http://localhost/wps/portal
Done.

2022-02-15 10:45 UTC, timpeteler approved these changes

2022-02-15 10:45 UTC, merged